server:
       basic:
             enable: false
       user:
            name: test
            password: 1234
       client:
              client-id: pjmall-frontend
              client-secret: 1234                   
         
